version: '3'
services:
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:v1.1.0
    ports:
      - '8050:8050'
      - '8051:8051'
    environment:
      - SMART_CONTRACT_VERIFIER__CONFIG=/app/config.toml
    volumes:
      ## optional: you can use default config or provide custom via file
      - ./config.toml:/app/config.toml
      ## optional: provide volume or folder to store compilers between launches
      - /tmp/compilers:/tmp/compilers
